/**
 * Writes `dist/` from `tokens.ts`, and writes nothing if the contrast contract breaks.
 * `--check` writes nothing and fails if `dist/` is stale.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { report } from "./contrast.ts";
import { providers } from "./providers.ts";
import {
  chrome,
  color,
  contrastContract,
  font,
  motion,
  radius,
  space,
  text,
  type ColorName,
  type Hex,
} from "./tokens.ts";

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolve(here, "../dist");
const check = process.argv.includes("--check");

const BANNER = `Generated by @convenux/design-system — do not edit.
Change src/tokens.ts and run \`npm run build\`.`;

/* -- tokens.css ------------------------------------------------------------ */

/** A Tailwind v4 `@theme` block. The `--font-*` variables come from each app's next/font. */
function css(): string {
  const l = (s = "") => lines.push(s);
  const lines: string[] = [];

  l(`/*\n${BANNER}\n*/`);
  l();
  l("@theme {");

  l("  /* Type. `--font-manrope` and `--font-jetbrains-mono` come from next/font. */");
  l("  /* Each var() has its own fallback: an unset one would void the whole stack. */");
  l(
    `  --font-display: var(--font-manrope, ${font.display.stack[0]}), ${font.display.stack.join(", ")};`,
  );
  l(
    `  --font-sans: var(--font-manrope, ${font.sans.stack[0]}), ${font.sans.stack.join(", ")};`,
  );
  l(
    `  --font-mono: var(--font-jetbrains-mono, ${font.mono.stack[0]}), ${font.mono.stack.join(", ")};`,
  );
  l();

  l("  /* Surfaces, darkest first. A card on a card steps up, never down. */");
  for (const name of ["ink", "ink-2", "ink-3", "ink-4", "ink-5"] as const) {
    l(`  --color-${name}: ${color[name]};`);
  }
  l();

  l("  /* Hairlines are decorative (1.4.11 exempt). Controls use --color-control. */");
  for (const name of ["line-subtle", "line", "line-strong", "control"] as const) {
    l(`  --color-${name}: ${color[name]};`);
  }
  l();

  l("  /* Text, brightest first. fg-6 is the floor; there is deliberately no fg-7. */");
  for (const name of ["fg", "fg-2", "fg-3", "fg-4", "fg-5", "fg-6"] as const) {
    l(`  --color-${name}: ${color[name]};`);
  }
  l();

  l("  /* Violet — the one brand colour. */");
  for (const name of [
    "violet-300",
    "violet-400",
    "violet-500",
    "violet-600",
    "violet-tint",
    "violet-edge",
    "on-violet",
  ] as const) {
    l(`  --color-${name}: ${color[name]};`);
  }
  l();

  l("  /* Signals. Named for the hue; the meaning belongs to the component. */");
  for (const name of [
    "mint-400",
    "mint-tint",
    "mint-edge",
    "amber-400",
    "amber-tint",
    "amber-edge",
    "rose-400",
    "rose-tint",
    "rose-edge",
  ] as const) {
    l(`  --color-${name}: ${color[name]};`);
  }
  l();

  l("  /* A badge, a control, a field, a panel, a card, a pill. */");
  for (const [name, px] of Object.entries(radius)) {
    l(`  --radius-${name}: ${px}px;`);
  }
  l();

  l("  /* Chrome: the bar, the page width, the two control heights. */");
  l(`  --spacing-bar: ${chrome.bar.height}px;`);
  l(`  --container-shell: ${chrome.shell.reading}px;`);
  l(`  --container-shell-wide: ${chrome.shell.wide}px;`);
  l(`  --spacing-control-sm: ${chrome.control.sm}px;`);
  l(`  --spacing-control-md: ${chrome.control.md}px;`);
  l();

  l("  /* Easings. Keyframes stay in each app — see tokens.ts. */");
  l(`  --ease-snap: ${motion["ease-snap"]};`);
  l(`  --ease-flow: ${motion["ease-flow"]};`);
  for (const [name, ms] of Object.entries(motion.duration)) {
    l(`  --duration-${name}: ${ms}ms;`);
  }
  l();

  l("  /* The type scale. */");
  for (const [name, { size, leading }] of Object.entries(text)) {
    l(`  --text-${name}: ${size}px;`);
    l(`  --text-${name}--line-height: ${leading};`);
  }

  l("}");
  l();
  return lines.join("\n");
}

/* -- brand.css ------------------------------------------------------------- */

/** The base layer, and the chrome every site would otherwise rebuild, as classes. */
function brand(): string {
  const m = chrome.mark;
  const size = (key: keyof typeof m) => {
    const s = m[key];
    return `.brand--${key} {
    gap: ${s.gap}px;
  }
  .brand--${key} .brand__mark {
    width: ${s.icon}px;
    height: ${s.icon}px;
    border-radius: ${s.iconRadius}px;
  }
  .brand--${key} .brand__name {
    font-size: ${s.name}px;
  }`;
  };

  return `/*
${BANNER}
*/

@layer base {
  html {
    color-scheme: dark;
    scroll-behavior: smooth;
  }

  @media (prefers-reduced-motion: reduce) {
    html {
      scroll-behavior: auto;
    }
    *,
    *::before,
    *::after {
      animation-duration: 0.01ms !important;
      transition-duration: 0.01ms !important;
    }
  }

  body {
    background: var(--color-ink);
    color: var(--color-fg);
    font-family: var(--font-sans);
    -webkit-font-smoothing: antialiased;
    overflow-wrap: break-word;
  }

  /* The offset lets the page paint between ring and control, so it reads on violet too. */
  :focus-visible {
    outline: 2px solid var(--color-violet-500);
    outline-offset: 3px;
    border-radius: 6px;
  }

  @media (forced-colors: active) {
    :focus-visible {
      outline-color: Highlight;
    }
  }

  ::selection {
    background-color: var(--color-violet-500);
    color: var(--color-on-violet);
  }

  button:not(:disabled),
  [role="button"]:not([aria-disabled="true"]),
  summary {
    cursor: pointer;
  }

  input::placeholder,
  textarea::placeholder {
    color: var(--color-fg-4);
    opacity: 1;
  }

  input[type="date"],
  input[type="time"] {
    color-scheme: dark;
  }
}

/* iOS zooms into any focused field under 16px and stays zoomed. Unlayered to beat size utilities. */
@media (pointer: coarse) {
  input:not([type="checkbox"], [type="radio"], [type="range"], [type="color"]),
  select,
  textarea {
    font-size: 16px;
  }
}

@layer components {
  /* ---- the lockup ------------------------------------------------------- */

  .brand {
    display: inline-flex;
    align-items: center;
    flex: none;
  }

  .brand__mark {
    flex: none;
    /* A hairline of light, so the mark reads on any surface in the ink ramp. */
    box-shadow: inset 0 0 0 1px ${chrome.markRing};
    object-fit: cover;
  }

  .brand__name {
    font-family: var(--font-display);
    font-weight: 800;
    letter-spacing: ${chrome.nameTracking};
    line-height: 1;
    color: var(--color-fg);
    white-space: nowrap;
  }

  ${size("sm")}

  ${size("md")}

  ${size("lg")}

  /* ---- the bar ---------------------------------------------------------- */

  .appbar {
    position: sticky;
    top: 0;
    z-index: 30;
    border-bottom: 1px solid var(--color-line-subtle);
  }

  /* On a childless layer: backdrop-filter makes a containing block for fixed descendants. */
  .appbar::before {
    content: "";
    position: absolute;
    inset: 0;
    z-index: -1;
    background: color-mix(in oklab, var(--color-ink) ${chrome.bar.opacity}%, transparent);
    backdrop-filter: blur(${chrome.bar.blur}px);
  }

  .appbar__inner {
    display: flex;
    align-items: center;
    gap: 12px;
    min-height: ${chrome.bar.height}px;
    margin-inline: auto;
    padding-inline: 16px;
  }

  @media (width >= 40rem) {
    .appbar__inner {
      gap: 24px;
      padding-inline: 24px;
    }
  }

  @media (width >= 64rem) {
    .appbar__inner {
      padding-inline: 40px;
    }
  }

  .appbar__inner {
    max-width: ${chrome.shell.reading}px;
  }

  .appbar--wide .appbar__inner {
    max-width: ${chrome.shell.wide}px;
  }

  /* ---- navigation ------------------------------------------------------- */

  /* Filled only where a page is current: anchors read as text, routes as pills. */
  .navlink {
    display: inline-flex;
    align-items: center;
    height: ${chrome.control.sm}px;
    padding-inline: 12px;
    border-radius: var(--radius-pill);
    font-size: 13.5px;
    font-weight: 600;
    white-space: nowrap;
    color: var(--color-fg-3);
    text-decoration: none;
    transition: color 150ms var(--ease-snap), background-color 150ms var(--ease-snap);
  }

  .navlink:hover {
    color: var(--color-fg);
  }

  .navlink[aria-current="page"],
  .navlink[aria-current="true"] {
    background: var(--color-ink-3);
    color: var(--color-fg);
  }

  /* ---- the primary call to action --------------------------------------- */

  .cta {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    height: ${chrome.control.md}px;
    padding-inline: 20px;
    border-radius: var(--radius-pill);
    background: var(--color-violet-500);
    color: var(--color-on-violet);
    font-weight: 800;
    font-size: 14px;
    white-space: nowrap;
    text-decoration: none;
    transition: background-color 150ms var(--ease-snap), transform 150ms var(--ease-snap);
  }

  .cta:hover {
    background: var(--color-violet-600);
  }

  .cta:active {
    transform: scale(0.97);
  }

  /* Inside chrome, where it sits beside other targets rather than alone. */
  .cta--sm {
    height: ${chrome.control.sm}px;
    padding-inline: 14px;
    font-size: 13px;
  }

  @media (prefers-reduced-motion: reduce) {
    .cta:active {
      transform: none;
    }
  }

  .cta--secondary {
    background: transparent;
    color: var(--color-fg);
    box-shadow: inset 0 0 0 1px var(--color-line-strong);
  }

  .cta--secondary:hover {
    background: var(--color-ink-3);
  }

  .cta--danger {
    background: var(--color-rose-tint);
    color: var(--color-rose-400);
    box-shadow: inset 0 0 0 1px var(--color-rose-edge);
  }

  .cta--danger:hover {
    background: var(--color-rose-tint);
    filter: brightness(1.25);
  }

  .cta:disabled,
  .cta[aria-disabled="true"] {
    opacity: 0.5;
    pointer-events: none;
  }

  /* ---- text ------------------------------------------------------------- */

  /* A field's name, a column head: mono, because a machine named it. */
  .label {
    font-family: var(--font-mono);
    font-size: 10px;
    font-weight: 600;
    letter-spacing: 0.18em;
    text-transform: uppercase;
    color: var(--color-fg-5);
  }

  /* The small line above a page's heading. */
  .eyebrow {
    font-family: var(--font-mono);
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 0.2em;
    text-transform: uppercase;
    color: var(--color-violet-400);
  }

  /* ---- fields ----------------------------------------------------------- */

  /* Keeps the page's focus ring: a border change alone is too faint to find a field by. */
  .field {
    width: 100%;
    min-height: ${chrome.control.md}px;
    padding: 12px 16px;
    border: 1px solid var(--color-control);
    border-radius: var(--radius-field);
    background: var(--color-ink-4);
    color: var(--color-fg);
    font-size: 15px;
    font-weight: 600;
    transition: border-color 150ms var(--ease-snap);
  }

  .field:focus {
    border-color: var(--color-violet-500);
  }

  .field:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  /* ---- tags and notices ------------------------------------------------- */

  /* What a tone means belongs to each app; the pairs are the contrast contract's. */
  .tag {
    display: inline-block;
    padding: 4px 10px;
    border-radius: var(--radius-pill);
    background: var(--color-ink-4);
    color: var(--color-fg-3);
    font-family: var(--font-mono);
    font-size: 10px;
    font-weight: 700;
    line-height: 1;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    white-space: nowrap;
  }

${(["violet", "mint", "amber", "rose"] as const)
  .map(
    (hue) => `  .tag--${hue} {
    background: var(--color-${hue}-tint);
    color: var(--color-${hue}-${hue === "violet" ? 300 : 400});
    box-shadow: inset 0 0 0 1px var(--color-${hue}-edge);
  }`,
  )
  .join("\n\n")}

  .alert {
    padding: 12px 16px;
    border: 1px solid var(--color-rose-edge);
    border-radius: var(--radius-sm);
    background: var(--color-rose-tint);
    color: var(--color-rose-400);
    font-size: 14px;
  }

  .alert--ok {
    border-color: var(--color-mint-edge);
    background: var(--color-mint-tint);
    color: var(--color-mint-400);
  }

  /* ---- skip link -------------------------------------------------------- */

  .skip-link {
    position: absolute;
    top: 12px;
    left: 12px;
    z-index: 60;
    padding: 10px 16px;
    border-radius: var(--radius-pill);
    background: var(--color-violet-500);
    color: var(--color-on-violet);
    font-weight: 800;
    font-size: 14px;
    transform: translateY(-200%);
  }

  .skip-link:focus {
    transform: none;
  }

  /* ---- sign-in buttons -------------------------------------------------- */

  /*
   * Each in its provider's colours, mark and wording, all one size. Apple's rules set
   * it: title at 43% of the height, logo at the full height of its artwork. System font.
   */
  .signin-list {
    container-type: inline-size;
    display: flex;
    flex-direction: column;
    gap: 10px;
    margin: 0;
    padding: 0;
    list-style: none;
  }

  .signin {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 4px;
    height: 40px;
    padding-inline: 12px;
    border-radius: var(--radius-field);
    font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
    font-size: 17px;
    font-weight: 500;
    white-space: nowrap;
    text-decoration: none;
    transition: filter 150ms var(--ease-snap);
  }

  .signin:hover {
    filter: brightness(0.95);
  }

  /* The slot Apple's artwork defines, 31 x 44, at the button's full height. */
  .signin__mark {
    flex: none;
    height: 100%;
    aspect-ratio: 31 / 44;
  }

  @container (min-width: 18rem) {
    .signin {
      height: 44px;
      font-size: 19px;
    }
  }

${Object.entries(providers)
  .map(
    ([key, p]) => `  .signin--${key} {
    background: ${p.background};
    color: ${p.foreground};${p.border ? `\n    box-shadow: inset 0 0 0 1px ${p.border};` : ""}
  }`,
  )
  .join("\n\n")}
}
`;
}

/* -- providers.js and providers.d.ts --------------------------------------- */

/** A 24-grid mark placed in Apple's 31 x 44 slot at 20 of 44 (Google's G at its specified 18 of 40). */
const SLOT = { viewBox: "0 0 31 44", glyph: "translate(5.5 12) scale(0.8333)" };

function providersJs(): string {
  return `/**
 * ${BANNER.split("\n").join("\n * ")}
 */

export const providers = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(providers).map(([key, p]) => [key, { ...p, glyph: key === "apple" ? null : SLOT.glyph }]),
    ),
    null,
    2,
  )};

export const slot = ${JSON.stringify(SLOT)};
`;
}

function providersDts(): string {
  return `/**
 * ${BANNER.split("\n").join("\n * ")}
 */

export type Path = { d: string; fill?: string };
export type Provider = {
  name: string;
  background: string;
  foreground: string;
  border?: string;
  viewBox: string;
  mark: Path[];
  /** The transform that places the mark in \`slot.viewBox\`; null for Apple, drawn on that grid. */
  glyph: string | null;
};
export type ProviderKey = ${Object.keys(providers)
    .map((k) => `"${k}"`)
    .join(" | ")};

export declare const providers: Record<ProviderKey, Provider>;
export declare const slot: { viewBox: string; glyph: string };
`;
}

/* -- native.js and native.d.ts --------------------------------------------- */

/**
 * React Native gets plain values. One family per weight rather than a `fontWeight`:
 * Android picks the wrong file once a family ships more than two faces.
 */
const MANROPE_FACES: Record<number, string> = {
  400: "Regular",
  500: "Medium",
  600: "SemiBold",
  700: "Bold",
  800: "ExtraBold",
};

const MONO_FACES: Record<number, string> = {
  400: "Regular",
  500: "Medium",
  600: "SemiBold",
  700: "Bold",
};

const faces = (
  weights: readonly number[],
  exportPrefix: string,
  names: Record<number, string>,
) => weights.map((w) => `    ${w}: "${exportPrefix}_${w}${names[w]}",`).join("\n");

/** The shared object literals, identical in the runtime and the declarations. */
function nativeData(): Record<string, string> {
  return {
    color: Object.entries(color)
      .map(([name, hex]) => `  "${name}": "${hex}",`)
      .join("\n"),
    radius: Object.entries(radius)
      .map(([name, px]) => `  ${name}: ${px},`)
      .join("\n"),
    space: Object.entries(space)
      .map(([step, px]) => `  "${step}": ${px},`)
      .join("\n"),
    text: Object.entries(text)
      .map(
        ([name, { size, leading }]) =>
          `  "${name}": { fontSize: ${size}, lineHeight: ${Math.round(size * leading)} },`,
      )
      .join("\n"),
    duration: Object.entries(motion.duration)
      .map(([name, ms]) => `  ${name}: ${ms},`)
      .join("\n"),
    markSizes: Object.entries(chrome.mark)
      .map(
        ([k, v]) =>
          `    ${k}: { icon: ${v.icon}, iconRadius: ${v.iconRadius}, name: ${v.name}, gap: ${v.gap} },`,
      )
      .join("\n"),
  };
}

/** The runtime the phone app imports: plain ESM, typed by native.d.ts. */
function nativeJs(): string {
  const d = nativeData();
  return `/**
 * ${BANNER.split("\n").join("\n * ")}
 */

export const color = {
${d.color}
};

export const radius = {
${d.radius}
};

export const space = {
${d.space}
};

/** One font file per weight, named as \`@expo-google-fonts/*\` exports them. */
export const face = {
  display: {
${faces(font.display.weights, "Manrope", MANROPE_FACES)}
  },
  sans: {
${faces(font.sans.weights, "Manrope", MANROPE_FACES)}
  },
  mono: {
${faces(font.mono.weights, "JetBrainsMono", MONO_FACES)}
  },
};

export const text = {
${d.text}
};

export const chrome = {
  mark: {
${d.markSizes}
  },
  markRing: "${chrome.markRing}",
  nameTracking: ${chrome.nameTracking.replace("em", "")},
  barHeight: ${chrome.bar.height},
  control: { sm: ${chrome.control.sm}, md: ${chrome.control.md} },
};

export const duration = {
${d.duration}
};

/** A size off the scale in a real face at a real weight; never set fontSize alone. */
export function type(size, weight, role = "sans") {
  return { ...text[size], fontFamily: face[role][weight ?? Math.min(...Object.keys(face[role]).map(Number))] };
}
`;
}

/** The declarations for the runtime above. */
function nativeDts(): string {
  const d = nativeData();
  return `/**
 * ${BANNER.split("\n").join("\n * ")}
 */

export declare const color: {
${d.color}
};
export type ColorName = keyof typeof color;

export declare const radius: {
${d.radius}
};

export declare const space: {
${d.space}
};

export declare const face: {
  display: {
${faces(font.display.weights, "Manrope", MANROPE_FACES)}
  };
  sans: {
${faces(font.sans.weights, "Manrope", MANROPE_FACES)}
  };
  mono: {
${faces(font.mono.weights, "JetBrainsMono", MONO_FACES)}
  };
};
export type Role = keyof typeof face;
export type Weight<R extends Role> = keyof (typeof face)[R];

export declare const text: {
${d.text}
};
export type TextSize = keyof typeof text;

export declare const chrome: {
  mark: {
${d.markSizes}
  };
  markRing: string;
  /** In em: multiply by the font size for React Native's letterSpacing. */
  nameTracking: number;
  barHeight: number;
  control: { sm: number; md: number };
};

export declare const duration: {
${d.duration}
};

export declare function type<R extends Role = "sans">(
  size: TextSize,
  weight?: Weight<R>,
  role?: R,
): { fontSize: number; lineHeight: number; fontFamily: string };
`;
}

/* -- the contract ---------------------------------------------------------- */

function audit(): { failures: string[]; rows: string[] } {
  const failures: string[] = [];
  const rows: string[] = [];

  for (const pair of contrastContract) {
    const fg = color[pair.fg as ColorName] as Hex;
    const bg = color[pair.bg as ColorName] as Hex;
    const got = Number(report(fg, bg));
    const ok = got >= pair.min;
    rows.push(
      `${ok ? "  ok " : "FAIL"} ${pair.fg.padEnd(11)} on ${pair.bg.padEnd(11)} ${String(
        got,
      ).padStart(5)}:1  (needs ${pair.min}) — ${pair.note}`,
    );
    if (!ok) {
      failures.push(
        `${pair.fg} on ${pair.bg} is ${got}:1, below the ${pair.min}:1 this pair needs (${pair.note}).`,
      );
    }
  }
  return { failures, rows };
}

/* -- write ----------------------------------------------------------------- */

const TARGETS: { file: string; body: string }[] = [
  { file: "tokens.css", body: css() },
  { file: "brand.css", body: brand() },
  { file: "native.js", body: nativeJs() },
  { file: "native.d.ts", body: nativeDts() },
  { file: "providers.js", body: providersJs() },
  { file: "providers.d.ts", body: providersDts() },
];

const { failures, rows } = audit();
console.log(rows.join("\n"));
console.log();

if (failures.length) {
  console.error(
    `Contrast contract broken — nothing written:\n  ${failures.join("\n  ")}`,
  );
  process.exit(1);
}
console.log(`Contrast contract holds across ${contrastContract.length} pairs.`);

if (!check) mkdirSync(dist, { recursive: true });

let stale = 0;
for (const target of TARGETS) {
  const path = join(dist, target.file);
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === target.body) {
    console.log(`  = ${target.file}`);
    continue;
  }
  stale++;
  if (check) {
    console.log(`  ! ${target.file}: STALE`);
    continue;
  }
  writeFileSync(path, target.body);
  console.log(`  → ${target.file}`);
}

if (check && stale) {
  console.error(
    `\n${stale} file(s) in dist/ are stale. Run \`npm run build\` and commit nothing —` +
      ` dist/ is built on publish.`,
  );
  process.exit(1);
}
