/**
 * Turns `tokens.ts` into the artefacts this package publishes, and refuses to write
 * any of them if the contrast contract is broken.
 *
 *   npm run build          # write dist/
 *   npm run build -- --check   # write nothing; fail if dist/ is stale
 *
 * Everything lands in `dist/`, which is what ships and what consumers import. The
 * generator used to write directly into three sibling checkouts; it does not know
 * about consumers any more, and they depend on the package instead.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { report } from "./contrast.ts";
import {
  chrome,
  color,
  contrastContract,
  font,
  motion,
  radius,
  space,
  text,
  type ColorName,
  type Hex,
} from "./tokens.ts";

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolve(here, "../dist");
const check = process.argv.includes("--check");

const BANNER = `Generated by @convenux/design-system — do not edit.
Change src/tokens.ts and run \`npm run build\`.`;

/* -- tokens.css ------------------------------------------------------------ */

/**
 * A Tailwind v4 `@theme` block.
 *
 * The font stacks front a `--font-*` variable that each app sets from `next/font`,
 * so the family names live here and the loading stays where Next can optimise it.
 */
function css(): string {
  const l = (s = "") => lines.push(s);
  const lines: string[] = [];

  l(`/*\n${BANNER}\n*/`);
  l();
  l("@theme {");

  l("  /* Type. `--font-manrope` and `--font-jetbrains-mono` come from next/font. */");
  l("  /*");
  l("   * Each var() carries its own fallback on purpose. A bare var() naming a");
  l("   * property the app never set is invalid at computed-value time, and takes the");
  l("   * whole declaration down with it rather than falling through to the next name");
  l("   * in the list — so an app that loads no mono face would lose `font-mono`");
  l("   * entirely instead of landing on the system monospace.");
  l("   */");
  l(
    `  --font-display: var(--font-manrope, ${font.display.stack[0]}), ${font.display.stack.join(", ")};`,
  );
  l(
    `  --font-sans: var(--font-manrope, ${font.sans.stack[0]}), ${font.sans.stack.join(", ")};`,
  );
  l(
    `  --font-mono: var(--font-jetbrains-mono, ${font.mono.stack[0]}), ${font.mono.stack.join(", ")};`,
  );
  l();

  l("  /* Surfaces, darkest first. A card on a card steps up, never down. */");
  for (const name of ["ink", "ink-2", "ink-3", "ink-4", "ink-5"] as const) {
    l(`  --color-${name}: ${color[name]};`);
  }
  l();

  l("  /* Hairlines are decorative (1.4.11 exempt). Controls use --color-control. */");
  for (const name of ["line-subtle", "line", "line-strong", "control"] as const) {
    l(`  --color-${name}: ${color[name]};`);
  }
  l();

  l("  /* Text, brightest first. fg-6 is the floor; there is deliberately no fg-7. */");
  for (const name of ["fg", "fg-2", "fg-3", "fg-4", "fg-5", "fg-6"] as const) {
    l(`  --color-${name}: ${color[name]};`);
  }
  l();

  l("  /* Violet — the one brand colour. */");
  for (const name of [
    "violet-300",
    "violet-400",
    "violet-500",
    "violet-600",
    "violet-tint",
    "violet-edge",
    "on-violet",
  ] as const) {
    l(`  --color-${name}: ${color[name]};`);
  }
  l();

  l("  /* Signals. Named for the hue; the meaning belongs to the component. */");
  for (const name of [
    "mint-400",
    "mint-tint",
    "mint-edge",
    "amber-400",
    "amber-tint",
    "amber-edge",
    "rose-400",
    "rose-tint",
    "rose-edge",
  ] as const) {
    l(`  --color-${name}: ${color[name]};`);
  }
  l();

  l("  /* A badge, a control, a field, a panel, a card, a pill. */");
  for (const [name, px] of Object.entries(radius)) {
    l(`  --radius-${name}: ${px}px;`);
  }
  l();

  l("  /* Chrome: the bar, the page width, the two control heights. */");
  l(`  --spacing-bar: ${chrome.bar.height}px;`);
  l(`  --container-shell: ${chrome.shell.reading}px;`);
  l(`  --container-shell-wide: ${chrome.shell.wide}px;`);
  l(`  --spacing-control-sm: ${chrome.control.sm}px;`);
  l(`  --spacing-control-md: ${chrome.control.md}px;`);
  l();

  l("  /* Easings. Keyframes stay in each app — see tokens.ts. */");
  l(`  --ease-snap: ${motion["ease-snap"]};`);
  l(`  --ease-flow: ${motion["ease-flow"]};`);
  for (const [name, ms] of Object.entries(motion.duration)) {
    l(`  --duration-${name}: ${ms}ms;`);
  }
  l();

  l("  /* The type scale. */");
  for (const [name, { size, leading }] of Object.entries(text)) {
    l(`  --text-${name}: ${size}px;`);
    l(`  --text-${name}--line-height: ${leading};`);
  }

  l("}");
  l();
  return lines.join("\n");
}

/* -- brand.css ------------------------------------------------------------- */

/**
 * The parts of the page that are the product rather than its content, as classes.
 *
 * These are components, which the rest of this system deliberately is not. They earn
 * the exception by being the thing tokens could not fix: two apps given the same
 * colours and the same faces still drew two different wordmarks, because a wordmark
 * is a composition, not a value. Anything that is genuinely one app's own stays in
 * that app's `globals.css`.
 */
function brand(): string {
  const m = chrome.mark;
  const size = (key: keyof typeof m) => {
    const s = m[key];
    return `.brand--${key} {
    gap: ${s.gap}px;
  }
  .brand--${key} .brand__mark {
    width: ${s.icon}px;
    height: ${s.icon}px;
    border-radius: ${s.iconRadius}px;
  }
  .brand--${key} .brand__name {
    font-size: ${s.name}px;
  }`;
  };

  return `/*
${BANNER}
*/

@layer components {
  /* ---- the lockup ------------------------------------------------------- */

  /*
   * The mark, a gap, the name. Always this order, always the sans face, always
   * title case: "CONVENUX" in mono read as a field name on a site where the mono
   * face means a machine produced the value.
   */
  .brand {
    display: inline-flex;
    align-items: center;
    flex: none;
  }

  .brand__mark {
    flex: none;
    /* A hairline of light, so the mark reads on any surface in the ink ramp. */
    box-shadow: inset 0 0 0 1px ${chrome.markRing};
    object-fit: cover;
  }

  .brand__name {
    font-family: var(--font-display);
    font-weight: 800;
    letter-spacing: ${chrome.nameTracking};
    line-height: 1;
    color: var(--color-fg);
    white-space: nowrap;
  }

  ${size("sm")}

  ${size("md")}

  ${size("lg")}

  /* ---- the bar ---------------------------------------------------------- */

  .appbar {
    position: sticky;
    top: 0;
    z-index: 30;
    border-bottom: 1px solid var(--color-line-subtle);
  }

  /*
   * The blur lives on a pseudo-element, not on .appbar itself, and that is
   * load-bearing rather than tidy: backdrop-filter establishes a containing block
   * for every fixed-position descendant. With it on the bar, a menu sheet inside
   * the header resolved a fixed, bottom-anchored sheet against the 60px bar and
   * rendered above the top of the screen. Keep the filter on a childless layer.
   */
  .appbar::before {
    content: "";
    position: absolute;
    inset: 0;
    z-index: -1;
    background: color-mix(in oklab, var(--color-ink) ${chrome.bar.opacity}%, transparent);
    backdrop-filter: blur(${chrome.bar.blur}px);
  }

  .appbar__inner {
    display: flex;
    align-items: center;
    gap: 12px;
    min-height: ${chrome.bar.height}px;
    margin-inline: auto;
    padding-inline: 16px;
  }

  @media (width >= 40rem) {
    .appbar__inner {
      gap: 24px;
      padding-inline: 24px;
    }
  }

  @media (width >= 64rem) {
    .appbar__inner {
      padding-inline: 40px;
    }
  }

  /* Marketing reads badly past ~1180; a table of editions wants all of 1440. */
  .appbar__inner {
    max-width: ${chrome.shell.reading}px;
  }

  .appbar--wide .appbar__inner {
    max-width: ${chrome.shell.wide}px;
  }

  /* ---- navigation ------------------------------------------------------- */

  /*
   * One nav link. The filled state only ever shows where a page can be current, so
   * a marketing header of anchors renders as plain text and a product header of
   * routes renders as pills, from the same class.
   */
  .navlink {
    display: inline-flex;
    align-items: center;
    height: ${chrome.control.sm}px;
    padding-inline: 12px;
    border-radius: var(--radius-pill);
    font-size: 13.5px;
    font-weight: 600;
    white-space: nowrap;
    color: var(--color-fg-3);
    text-decoration: none;
    transition: color 150ms var(--ease-snap), background-color 150ms var(--ease-snap);
  }

  .navlink:hover {
    color: var(--color-fg);
  }

  .navlink[aria-current="page"],
  .navlink[aria-current="true"] {
    background: var(--color-ink-3);
    color: var(--color-fg);
  }

  /* ---- the primary call to action --------------------------------------- */

  /*
   * A pill, in all three products. The database already spoke in pills everywhere
   * and the marketing site's 12px-radius button was the odd one out.
   */
  .cta {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    height: ${chrome.control.md}px;
    padding-inline: 20px;
    border-radius: var(--radius-pill);
    background: var(--color-violet-500);
    color: var(--color-on-violet);
    font-weight: 800;
    font-size: 14px;
    white-space: nowrap;
    text-decoration: none;
    transition: background-color 150ms var(--ease-snap), transform 150ms var(--ease-snap);
  }

  .cta:hover {
    background: var(--color-violet-600);
  }

  .cta:active {
    transform: scale(0.97);
  }

  /* Inside chrome, where it sits beside other targets rather than alone. */
  .cta--sm {
    height: ${chrome.control.sm}px;
    padding-inline: 14px;
    font-size: 13px;
  }

  @media (prefers-reduced-motion: reduce) {
    .cta:active {
      transform: none;
    }
  }
}
`;
}

/* -- native.js and native.d.ts --------------------------------------------- */

/**
 * React Native has no cascade and no custom properties, so the same tokens ship as
 * plain values.
 *
 * Weights are separate families rather than a `fontWeight`: Android picks the wrong
 * file for anything but 400 and 700 when a family has more than two faces, and
 * Manrope ships five. `sans(600)` names the file directly and is right everywhere.
 */
const MANROPE_FACES: Record<number, string> = {
  400: "Regular",
  500: "Medium",
  600: "SemiBold",
  700: "Bold",
  800: "ExtraBold",
};

const MONO_FACES: Record<number, string> = {
  400: "Regular",
  500: "Medium",
  600: "SemiBold",
  700: "Bold",
};

const faces = (
  weights: readonly number[],
  exportPrefix: string,
  names: Record<number, string>,
) => weights.map((w) => `    ${w}: "${exportPrefix}_${w}${names[w]}",`).join("\n");

/** The shared object literals, identical in the runtime and the declarations. */
function nativeData(): Record<string, string> {
  return {
    color: Object.entries(color)
      .map(([name, hex]) => `  "${name}": "${hex}",`)
      .join("\n"),
    radius: Object.entries(radius)
      .map(([name, px]) => `  ${name}: ${px},`)
      .join("\n"),
    space: Object.entries(space)
      .map(([step, px]) => `  "${step}": ${px},`)
      .join("\n"),
    text: Object.entries(text)
      .map(
        ([name, { size, leading }]) =>
          `  "${name}": { fontSize: ${size}, lineHeight: ${Math.round(size * leading)} },`,
      )
      .join("\n"),
    duration: Object.entries(motion.duration)
      .map(([name, ms]) => `  ${name}: ${ms},`)
      .join("\n"),
    markSizes: Object.entries(chrome.mark)
      .map(
        ([k, v]) =>
          `    ${k}: { icon: ${v.icon}, iconRadius: ${v.iconRadius}, name: ${v.name}, gap: ${v.gap} },`,
      )
      .join("\n"),
  };
}

/**
 * The runtime the phone app imports.
 *
 * Plain ESM rather than TypeScript: this ships inside a package, and a consumer's
 * bundler should not have to compile anything out of node_modules to use it. The
 * types travel alongside in native.d.ts.
 *
 * Weights are separate font families rather than a `fontWeight`, because Android
 * resolves `fontWeight` to the wrong file once a family ships more than two faces,
 * and Manrope ships five here.
 */
function nativeJs(): string {
  const d = nativeData();
  return `/**
 * ${BANNER.split("\n").join("\n * ")}
 */

export const color = {
${d.color}
};

export const radius = {
${d.radius}
};

export const space = {
${d.space}
};

/** One font file per weight, named as \`@expo-google-fonts/*\` exports them. */
export const face = {
  display: {
${faces(font.display.weights, "Manrope", MANROPE_FACES)}
  },
  sans: {
${faces(font.sans.weights, "Manrope", MANROPE_FACES)}
  },
  mono: {
${faces(font.mono.weights, "JetBrainsMono", MONO_FACES)}
  },
};

export const text = {
${d.text}
};

export const chrome = {
  mark: {
${d.markSizes}
  },
  markRing: "${chrome.markRing}",
  nameTracking: ${chrome.nameTracking.replace("em", "")},
  barHeight: ${chrome.bar.height},
  control: { sm: ${chrome.control.sm}, md: ${chrome.control.md} },
};

export const duration = {
${d.duration}
};

/**
 * A complete text style: a size off the scale, in a real face, at a real weight.
 *
 * Anything that renders words should come through here rather than setting
 * \`fontSize\` and \`fontFamily\` separately, which is how nine screens once ended up
 * in the system sans.
 */
export function type(size, weight = 400, role = "sans") {
  return { ...text[size], fontFamily: face[role][weight] };
}
`;
}

/** The declarations for the runtime above. */
function nativeDts(): string {
  const d = nativeData();
  return `/**
 * ${BANNER.split("\n").join("\n * ")}
 */

export declare const color: {
${d.color}
};
export type ColorName = keyof typeof color;

export declare const radius: {
${d.radius}
};

export declare const space: {
${d.space}
};

export declare const face: {
  display: {
${faces(font.display.weights, "Manrope", MANROPE_FACES)}
  };
  sans: {
${faces(font.sans.weights, "Manrope", MANROPE_FACES)}
  };
  mono: {
${faces(font.mono.weights, "JetBrainsMono", MONO_FACES)}
  };
};
export type Role = keyof typeof face;
export type Weight<R extends Role> = keyof (typeof face)[R];

export declare const text: {
${d.text}
};
export type TextSize = keyof typeof text;

export declare const chrome: {
  mark: {
${d.markSizes}
  };
  markRing: string;
  nameTracking: number;
  barHeight: number;
  control: { sm: number; md: number };
};

export declare const duration: {
${d.duration}
};

export declare function type<R extends Role = "sans">(
  size: TextSize,
  weight?: Weight<R>,
  role?: R,
): { fontSize: number; lineHeight: number; fontFamily: string };
`;
}

/* -- the contract ---------------------------------------------------------- */

function audit(): { failures: string[]; rows: string[] } {
  const failures: string[] = [];
  const rows: string[] = [];

  for (const pair of contrastContract) {
    const fg = color[pair.fg as ColorName] as Hex;
    const bg = color[pair.bg as ColorName] as Hex;
    const got = Number(report(fg, bg));
    const ok = got >= pair.min;
    rows.push(
      `${ok ? "  ok " : "FAIL"} ${pair.fg.padEnd(11)} on ${pair.bg.padEnd(11)} ${String(
        got,
      ).padStart(5)}:1  (needs ${pair.min}) — ${pair.note}`,
    );
    if (!ok) {
      failures.push(
        `${pair.fg} on ${pair.bg} is ${got}:1, below the ${pair.min}:1 this pair needs (${pair.note}).`,
      );
    }
  }
  return { failures, rows };
}

/* -- write ----------------------------------------------------------------- */

const TARGETS: { file: string; body: string }[] = [
  { file: "tokens.css", body: css() },
  { file: "brand.css", body: brand() },
  { file: "native.js", body: nativeJs() },
  { file: "native.d.ts", body: nativeDts() },
];

const { failures, rows } = audit();
console.log(rows.join("\n"));
console.log();

if (failures.length) {
  console.error(
    `Contrast contract broken — nothing written:\n  ${failures.join("\n  ")}`,
  );
  process.exit(1);
}
console.log(`Contrast contract holds across ${contrastContract.length} pairs.`);

if (!check) mkdirSync(dist, { recursive: true });

let stale = 0;
for (const target of TARGETS) {
  const path = join(dist, target.file);
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === target.body) {
    console.log(`  = ${target.file}`);
    continue;
  }
  stale++;
  if (check) {
    console.log(`  ! ${target.file}: STALE`);
    continue;
  }
  writeFileSync(path, target.body);
  console.log(`  → ${target.file}`);
}

if (check && stale) {
  console.error(
    `\n${stale} file(s) in dist/ are stale. Run \`npm run build\` and commit nothing —` +
      ` dist/ is built on publish.`,
  );
  process.exit(1);
}
